### ISSUE TITLE
DNS resolution issues when built on Windows

### ISSUE THREAD

**Issue by danielghurley** [shaunduncan/packer-provisioner-host-command#3]
Have you encountered any problems with DNS resolution for running commands on Windows?  I'm getting issues where the plugin builds (natively) and runs OK, except that any command requiring DNS resolution fails.  The same issue does not happen on Linux (amd64) systems.  

DNS resolution across platforms appears to be a bit problematic with Go (e.g. https://code.google.com/p/go/issues/detail?id=6336, although this is a glibc bug), so I suspect this is an issue with os/exec.

**Comment by shaunduncan** [comment]
Thanks for bringing this up. I haven't personally done a lot of experimentation on Windows, so I will likely need to do a bit of experimentation. Do you have a test scenario that seems to reproduce the issue?
