### ISSUE TITLE
incompatible with new API version

### ISSUE THREAD

**Issue by jantman** [shaunduncan/packer-provisioner-host-command#6]
plugin API version 4 is out. This plugin seems to no longer work with packer build from master.

**Comment by shaunduncan** [comment]
Hmm, I didn't realize the API had changed. I'll have to dig around to see what I need to fix to make it work again.

**Comment by jantman** [comment]
I just realized this might be my fault... trying to dig into it more. Packer doesn't say *which* plugin is incompatible, just that one is, and this is the only non-stock one that I'm using...

**Comment by jantman** [comment]
FWIW, if I try to build now, with packer 0.7.5 installed from the official download, I'm seeing some issues when building. First I get errors about the github.com/mitchellh/multistep and github.com/mitchellh/go-fs packages missing. When I ``go get`` them and try to make, I get:

```
rm -f /home/jantman/tmp/packer-provisioner-host-command/src//bin/packer-provisioner-host-command
go get github.com/flynn/go-shlex
go get github.com/mitchellh/packer
go build -o /home/jantman/tmp/packer-provisioner-host-command/src//bin/packer-provisioner-host-command -a
# _/home/jantman/tmp/packer-provisioner-host-command
./host_command.go:44: undefined: packer.ConfigTemplate
Makefile:11: recipe for target 'build' failed
make: *** [build] Error 2
```

I downgraded my local ``packer`` to 0.6.1, which was what I was using when I started using this plugin. It works fine with this older version.

**Comment by shaunduncan** [comment]
Yeah I saw the same with ConfigTemplate. That's probably what the problem is. I'll have to dig into what changed to see what I can do to fix it.

**Comment by jantman** [comment]
Ok. No immediate major issue for me - I just installed 0.6.1 under a separate path - but it might be worth noting in the readme for the time being.
